'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Copy, Check, MessageCircle, ExternalLink, AlertTriangle, CheckCircle2, Search, Flag } from 'lucide-react'
import type { DecisionResult } from '@/types'
import toast from 'react-hot-toast'
import ShareButton from './ShareButton'
import ReportScamModal from './ReportScamModal'

interface Props {
  result: DecisionResult
  checkId?: string
  inputText?: string
}

const VERDICT_STYLES = {
  green:  { bg: 'bg-brand-green-light',  text: 'text-brand-green-dark',  accent: 'bg-brand-green',  border: 'border-brand-green/20',  dot: 'bg-brand-green' },
  yellow: { bg: 'bg-brand-yellow-light', text: 'text-brand-yellow-dark', accent: 'bg-brand-yellow', border: 'border-brand-yellow/20', dot: 'bg-brand-yellow' },
  red:    { bg: 'bg-brand-red-light',    text: 'text-brand-red-dark',    accent: 'bg-brand-red',    border: 'border-brand-red/20',    dot: 'bg-brand-red' },
}

function extractPhones(text: string): string[] {
  const matches = text.match(/(\+?63|0)9\d{9}/g) || []
  return [...new Set(matches.map(m => {
    if (m.startsWith('+639')) return '0' + m.slice(3)
    if (m.startsWith('639'))  return '0' + m.slice(2)
    return m
  }))]
}

function parseFinding(text: string): { observation: string; reason: string } | null {
  const idx = text.indexOf(' — REASON: ')
  if (idx === -1) {
    // Try alternate dash variants
    const alt = text.indexOf(' - REASON: ')
    if (alt === -1) return null
    const obs = text.slice(0, alt).replace(/^OBSERVATION:\s*/i, '').trim()
    const reason = text.slice(alt + ' - REASON: '.length).trim()
    return { observation: obs, reason }
  }
  const obs = text.slice(0, idx).replace(/^OBSERVATION:\s*/i, '').trim()
  const reason = text.slice(idx + ' — REASON: '.length).trim()
  return { observation: obs, reason }
}

export default function ResultClient({ result, checkId, inputText = '' }: Props) {
  const [lang, setLang] = useState<'en' | 'tl'>('en')
  const [copied, setCopied] = useState(false)
  const [checkedEvidence, setCheckedEvidence] = useState<Set<number>>(new Set())
  const [showReportFromChecklist, setShowReportFromChecklist] = useState(false)

  const v = VERDICT_STYLES[result.color]
  const L = (obj: { en: string; tl: string }) => obj[lang]
  const trustScore = 100 - result.score
  const detectedPhones = extractPhones(inputText)

  // aiInsights[0] = entitySummary, aiInsights[1] = headlineFinding
  const entitySummary   = result.aiInsights?.[0] || ''
  const headlineFinding = result.aiInsights?.[1] || ''

  // Split reasons into red flags vs positive indicators
  const redFlags   = result.reasons.filter(r => r.severity !== 'positive')
  const positives  = result.reasons.filter(r => r.severity === 'positive')

  function toggleEvidence(i: number) {
    setCheckedEvidence(prev => {
      const next = new Set(prev)
      next.has(i) ? next.delete(i) : next.add(i)
      return next
    })
  }

  async function copyReport() {
    const lines: string[] = [
      `LegitCheck PH — Risk Report`,
      `Trust Score: ${trustScore}/100`,
      `Verdict: ${L(result.headline)}`,
      ``,
    ]

    if (entitySummary) lines.push(`What we analyzed: ${entitySummary}`, ``)
    if (headlineFinding) lines.push(`Main conclusion: ${headlineFinding}`, ``)

    if (redFlags.length > 0) {
      lines.push(lang === 'tl' ? 'Mga Red Flag:' : 'Red flags found:')
      redFlags.forEach(r => {
        const parsed = parseFinding(L(r))
        if (parsed) lines.push(`• ${parsed.observation}\n  → ${parsed.reason}`)
        else lines.push(`• ${L(r)}`)
      })
      lines.push(``)
    }

    if (positives.length > 0) {
      lines.push(lang === 'tl' ? 'Positibong Senyales:' : 'Positive signals:')
      positives.forEach(r => {
        const parsed = parseFinding(L(r))
        lines.push(`• ${parsed ? parsed.observation : L(r)}`)
      })
      lines.push(``)
    }

    lines.push(
      lang === 'tl' ? 'Saan Mag-report:' : 'Report to:',
      ...result.reportChannels.map(c => `• ${c.name}${c.contact ? ' · ' + c.contact : ''}${c.url ? ' — ' + c.url : ''}`),
      ``,
      lang === 'tl' ? 'Gabay lang ito. Hindi ito legal o opisyal na desisyon.' : 'This is a guide only. Not a final legal, bank, platform, government, or law-enforcement decision.',
      `Generated by LegitCheck PH`,
    )

    await navigator.clipboard.writeText(lines.join('\n'))
    setCopied(true)
    toast.success('Report copied!')
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="min-h-screen bg-paper-2">
      {/* Nav */}
      <header className="border-b border-line bg-paper sticky top-0 z-50 px-4 py-3 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Link href="/buyer" className="text-ink-3 hover:text-ink transition-colors">
            <ArrowLeft size={18} />
          </Link>
          <div className="flex items-baseline gap-1">
            <span className="text-base font-medium text-ink">LegitCheck</span>
            <span className="text-base font-light text-ink-2">PH</span>
          </div>
        </div>
        <div className="flex bg-paper-2 border border-line rounded-full p-0.5">
          {(['en', 'tl'] as const).map(l => (
            <button key={l} onClick={() => setLang(l)}
              className={`px-3 py-1 rounded-full text-xs font-medium transition-all ${lang === l ? 'bg-paper text-ink shadow-sm border border-line' : 'text-ink-3'}`}>
              {l.toUpperCase()}
            </button>
          ))}
        </div>
      </header>

      <div className="max-w-lg mx-auto px-4 py-5 space-y-4 animate-slide-up">

        {/* ── Verdict card ─────────────────────────────────────────────────── */}
        <div className={`rounded-2xl overflow-hidden border ${v.border}`}>

          {/* Score + verdict header */}
          <div className={`${v.bg} px-5 py-6 text-center`}>
            <p className={`text-xs font-mono font-semibold uppercase tracking-widest mb-1 ${v.text} opacity-60`}>
              Trust Score · 0 = highest risk · 100 = fully safe
            </p>
            <div className="inline-flex items-baseline gap-1 mb-3">
              <span className={`text-6xl font-light font-mono tracking-tighter ${v.text}`}>{trustScore}</span>
              <span className="text-sm text-ink-3 font-mono">/100</span>
            </div>
            <div className="w-full max-w-[200px] mx-auto mb-4">
              <div className="h-2 rounded-full bg-black/10">
                <div className={`h-2 rounded-full ${v.accent} transition-all`} style={{ width: `${trustScore}%` }} />
              </div>
            </div>
            <div className={`text-xl font-semibold mb-1 ${v.text}`}>{L(result.headline)}</div>
            <div className={`text-sm mb-4 ${v.text} opacity-80`}>{L(result.subheadline)}</div>
            <span className={`inline-block ${v.accent} text-white text-sm font-semibold px-5 py-2.5 rounded-full`}>
              {L(result.action)}
            </span>
          </div>

          {/* ── Basis of Decision ──────────────────────────────────────────── */}
          <div className="bg-paper border-t border-line divide-y divide-line">

            <div className="px-4 py-4 space-y-4">
              <div className="sec-label">
                {lang === 'tl' ? `Bakit namin sincore ito ng ${trustScore}/100` : `Why we scored this ${trustScore}/100`}
              </div>

              {/* What we analyzed */}
              {entitySummary && (
                <div className="flex gap-2.5 items-start">
                  <Search size={14} className="text-ink-3 flex-shrink-0 mt-0.5" />
                  <div>
                    <p className="text-[11px] font-semibold uppercase tracking-wider text-ink-3 mb-0.5">
                      {lang === 'tl' ? 'Ano ang sinuri' : 'What we analyzed'}
                    </p>
                    <p className="text-sm text-ink-2 leading-snug">{entitySummary}</p>
                  </div>
                </div>
              )}

              {/* Main conclusion */}
              {headlineFinding && (
                <div className={`rounded-xl px-3.5 py-3 border ${
                  result.color === 'red'
                    ? 'bg-brand-red-light border-brand-red/20'
                    : result.color === 'green'
                      ? 'bg-brand-green-light border-brand-green/20'
                      : 'bg-brand-yellow-light border-brand-yellow/20'
                }`}>
                  <p className={`text-[11px] font-semibold uppercase tracking-wider mb-1 ${v.text} opacity-70`}>
                    {lang === 'tl' ? 'Pangunahing Konklusyon' : 'Main Conclusion'}
                  </p>
                  <p className={`text-sm font-medium leading-snug ${v.text}`}>{headlineFinding}</p>
                </div>
              )}

              {/* Red flags */}
              {redFlags.length > 0 && (
                <div className="space-y-2.5">
                  <p className="text-[11px] font-semibold uppercase tracking-wider text-ink-3 flex items-center gap-1.5">
                    <AlertTriangle size={11} className="text-brand-red opacity-80" />
                    {lang === 'tl' ? 'Mga Nakitang Red Flag' : 'Red Flags Found'}
                  </p>
                  {redFlags.map((r, i) => {
                    const parsed = parseFinding(L(r))
                    return (
                      <div key={i} className="bg-paper-2 border border-line rounded-xl px-3.5 py-3 space-y-1">
                        {parsed ? (
                          <>
                            <p className="text-sm font-medium text-ink leading-snug">{parsed.observation}</p>
                            <p className="text-xs text-ink-3 leading-relaxed">{parsed.reason}</p>
                          </>
                        ) : (
                          <p className="text-sm text-ink-2 leading-snug">{L(r)}</p>
                        )}
                      </div>
                    )
                  })}
                </div>
              )}

              {/* Positive indicators */}
              {positives.length > 0 && (
                <div className="space-y-2.5">
                  <p className="text-[11px] font-semibold uppercase tracking-wider text-ink-3 flex items-center gap-1.5">
                    <CheckCircle2 size={11} className="text-brand-green opacity-80" />
                    {lang === 'tl' ? 'Mga Positibong Senyales' : 'Positive Signals'}
                  </p>
                  {positives.map((r, i) => {
                    const parsed = parseFinding(L(r))
                    return (
                      <div key={i} className="bg-brand-green-light border border-brand-green/20 rounded-xl px-3.5 py-3 space-y-1">
                        {parsed ? (
                          <>
                            <p className="text-sm font-medium text-brand-green-dark leading-snug">{parsed.observation}</p>
                            <p className="text-xs text-brand-green-dark opacity-70 leading-relaxed">{parsed.reason}</p>
                          </>
                        ) : (
                          <p className="text-sm text-brand-green-dark leading-snug">{L(r)}</p>
                        )}
                      </div>
                    )
                  })}
                </div>
              )}

              {/* No findings fallback */}
              {redFlags.length === 0 && positives.length === 0 && !headlineFinding && (
                <p className="text-sm text-ink-3 italic">
                  {lang === 'tl'
                    ? 'Walang nakitang red flag sa ibinigay na content. Kung may hindi nasama, subukan ulit na may mas detalyadong impormasyon.'
                    : 'No specific findings in the content provided. Try again with the actual message, offer, or conversation for a more accurate assessment.'}
                </p>
              )}
            </div>

            {/* Report to */}
            <div className="px-4 py-4">
              <div className="sec-label mb-2">{lang === 'tl' ? 'Saan Mag-report' : 'Report to'}</div>
              <div className="flex flex-col gap-2">
                {result.reportChannels.map((ch, i) => (
                  <div key={i} className="flex items-center justify-between gap-2 text-sm">
                    <span className="text-ink-2 leading-snug">
                      {ch.name}{ch.contact ? <span className="text-ink-3 ml-1">· {ch.contact}</span> : null}
                    </span>
                    {ch.url && (
                      <a href={ch.url} target="_blank" rel="noopener noreferrer"
                        className="flex items-center gap-1 text-xs text-ink-3 hover:text-ink transition-colors whitespace-nowrap flex-shrink-0">
                        Visit <ExternalLink size={10} />
                      </a>
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* Evidence checklist */}
            <div className="px-4 py-4">
              <div className="sec-label">
                {lang === 'tl' ? 'Kung mag-re-report ka — ihanda ito:' : 'If you decide to report — gather these first:'}
              </div>
              <p className="text-xs text-ink-3 mt-1 mb-3">
                {lang === 'tl'
                  ? 'I-tick ang mga hawak mo, tapos pindutin ang Report para magsumite.'
                  : 'Tick what you have, then hit Report to submit to authorities.'}
              </p>
              <div className="space-y-2">
                {result.evidenceItems.map((e, i) => (
                  <button key={i} onClick={() => toggleEvidence(i)}
                    className="flex items-center gap-3 w-full text-left group">
                    <div className={`w-4 h-4 rounded-md border flex items-center justify-center flex-shrink-0 transition-all ${
                      checkedEvidence.has(i) ? 'bg-brand-green border-brand-green' : 'border-line bg-paper-2 group-hover:border-ink-3'
                    }`}>
                      {checkedEvidence.has(i) && <Check size={10} className="text-white" strokeWidth={3} />}
                    </div>
                    <span className="text-sm text-ink-2">{L(e)}</span>
                  </button>
                ))}
              </div>
              {checkedEvidence.size > 0 && (
                <button
                  onClick={() => setShowReportFromChecklist(true)}
                  className="mt-4 w-full flex items-center justify-center gap-2 py-2.5 rounded-xl bg-brand-red text-white text-sm font-medium hover:opacity-90 transition-all active:scale-95">
                  <Flag size={13} />
                  {lang === 'tl' ? `Mag-report — ${checkedEvidence.size} ebidensya handa` : `Report this — ${checkedEvidence.size} item${checkedEvidence.size > 1 ? 's' : ''} ready`}
                </button>
              )}
            </div>

          </div>
        </div>

        {/* Disclaimer */}
        <div className="border-l-2 border-line pl-3 py-1">
          <p className="text-xs text-ink-3 leading-relaxed">
            {lang === 'tl'
              ? 'Gabay lang ito. Hindi ito final legal, bank, platform, government, o law-enforcement decision. Mag-verify pa rin bago tumuloy.'
              : 'This is a guide only. Not a final legal, bank, platform, government, or law-enforcement decision. Verify further before proceeding.'}
          </p>
        </div>

        {/* Actions */}
        <div className="space-y-2">
          <button onClick={copyReport}
            className={`w-full flex items-center justify-center gap-2 py-3 rounded-xl border text-sm font-medium transition-all active:scale-95 ${
              copied ? 'bg-brand-green-light border-brand-green/20 text-brand-green-dark' : 'bg-paper border-line text-ink-2 hover:bg-ink hover:text-white hover:border-ink'
            }`}>
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? 'Copied!' : lang === 'tl' ? 'Kopyahin ang Report' : 'Copy report'}
          </button>

          {checkId && <ShareButton checkId={checkId} lang={lang} />}

          {checkId && (
            <Link href={`/dashboard/agents?checkId=${checkId}`}
              className="w-full flex items-center justify-center gap-2 py-3 rounded-xl border border-line bg-paper text-sm text-ink-2 hover:bg-ink hover:text-white hover:border-ink transition-all active:scale-95">
              <MessageCircle size={14} />
              Talk to FraudGuard AI
            </Link>
          )}

          <ReportScamModal
            checkId={checkId}
            categoryId={result.categoryId}
            detectedIdentifiers={detectedPhones}
            forceOpen={showReportFromChecklist}
            onClose={() => setShowReportFromChecklist(false)}
          />
        </div>

        <div className="pb-8" />
      </div>
    </div>
  )
}
